"$schema" = "https://json.schemastore.org/prettierrc"

experimentalTernaries = true
tabWidth = 2
useTabs = false
semi = true
singleQuote = false
quoteProps = "as-needed"
jsxSingleQuote = false
trailingComma = "es5"
bracketSpacing = true
bracketSameLine = false
arrowParens = "always"
insertPragma = false
proseWrap = "always"
htmlWhitespaceSensitivity = "css"
vueIndentScriptAndStyle = false
endOfLine = "lf"
embeddedLanguageFormatting = "auto"
singleAttributePerLine = false
