# $username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$docker_context$package$bun$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$golang$haskell$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$time$status$container$shell$character
"$schema" = 'https://starship.rs/config-schema.json'
# format = '$directory$git_branch$hostname$custom$character'
# right_format = '$cmd_duration$jobs$shlvl$status'
format = '''$directory$git_branch$git_status$hostname$localip$lua$python$rust $fill $git_metrics$cmd_duration$jobs$shlvl$status 
 $character'''
continuation_prompt = '[∙](bright-black) '
scan_timeout = 50
command_timeout = 200
add_newline = true

# LEFT PROMPT
[directory]
truncation_length = 1 # only tail is full length
fish_style_pwd_dir_length = 1
use_logical_path = true
format = ' [ $path](bold green)[$read_only](red)'
read_only = ' 󰌾'

[git_branch]
format = ' [ $branch](bold purple)'
truncation_length = 922
truncation_symbol = '…'
only_attached = false
always_show_remote = false

[git_metrics]
format = ' (\[[+$added]($added_style)\])(\[[-$deleted]($deleted_style)\])'
disabled = true
ignore_submodules = true

[git_status]
format = '$ahead_behind$staged[$conflicted](red)'
conflicted = ' [󰞇 $count](red)'
ahead = ' [ $count](cyan)'
behind = ' [ $count](green)'
staged = ' [ $count](green)'

[hostname]
format = ' [](yellow)'
ssh_only = true

[localip]
format = ' [$localipv4](yellow)'
ssh_only = true
disabled = false

# RIGHT PROMPT
[cmd_duration]
min_time = 20
format = '\[[$duration](cyan)\]'
show_milliseconds = false
show_notifications = false
min_time_to_notify = 45000

[jobs]
symbol_threshold = 1
number_threshold = 2
format = '\[[$symbol$number](blue)\]'
symbol = '✦'

[shlvl]
format = '\[[$symbol$shlvl](green)\]'
symbol = ''
disabled = false

[status]
format = '\[[$symbol$status](red)\]'
symbol = '✘'
success_symbol = ''
not_executable_symbol = '󰅚'
not_found_symbol = ''
sigint_symbol = '󰟾'
signal_symbol = '󱐋'
map_symbol = false
recognize_signal_code = true
pipestatus = true
pipestatus_separator = '|'
pipestatus_segment_format = '[$status](red)'
pipestatus_format = '\[$pipestatus\] -> [$symbol$common_meaning$signal_name$maybe_int](red)'
disabled = false

# SPECIAL
[lua]
format = ' [ lua](#51a0cf)'
lua_binary = 'luajit'
detect_files = []
detect_extensions = []

[python]
format = ' [ python](#ffbc03)'

[rust]
format = ' [ rust](#dea584)'
version_format = '$major.$minor'
detect_extensions = []

[fill]
symbol = '─'

[character]
format = '$symbol '
success_symbol = '[❯](bold)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_visual_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold red)'
vimcmd_replace_one_symbol = '[](bold red)'


