"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username$directory$git_branch \
$fill \
$status$git_status$git_metrics$cmd_duration$jobs$shlvl 
 $character"""
continuation_prompt = '[∙](bright-black) '
scan_timeout = 50
command_timeout = 200
add_newline = true


# LEFT PROMPT

[username]
format = ' [ $user](bright-yellow)'
show_always = false

[directory]
format = ' [ $before_root_path$repo_root$path](bold green)[$read_only](red)'
read_only = ' 󰌾'
truncation_length = 1
fish_style_pwd_dir_length = 1
use_logical_path = true

# truncate_to_repo = false
# truncation_symbol = '%'
# before_repo_root_style = "cyan"
# repo_root_style = "yellow"
# repo_root_format = "$before_root_path|$repo_root|$path"
# [directory.substitutions]
# "/data/data/com.termux/files/usr" = "prefix"

[git_branch]
format = ' [ $branch](bold purple)'


# RIGHT PROMPT

[status]
format = '\[[$symbol$status](red)\]'
pipestatus_segment_format = '[$status](red)'
pipestatus_format = '\[$pipestatus\]'
success_symbol = ''
symbol = '✘'
pipestatus_separator = '|'
not_executable_symbol = '󰅚'
not_found_symbol = ''
sigint_symbol = '󰟾'
signal_symbol = '󱐋'
map_symbol = false
recognize_signal_code = true
pipestatus = true
disabled = false

[git_status]
format = '$ahead_behind$staged$conflicted$stashed'
ahead = '\[[ $count](bright-cyan)\]'
behind = '\[[ $count](green)\]'
staged = '\[[ $count](green)\]'
conflicted = '\[[󰞇 $count](red)\]'
stashed = '\[[ $count](bright-yellow)\]'

[git_metrics]
format = '(\[[+$added]($added_style)\])(\[[-$deleted]($deleted_style)\])'
disabled = true
ignore_submodules = true

[cmd_duration]
format = '\[[$duration](cyan)\]'
min_time = 5
show_milliseconds = false
show_notifications = false
min_time_to_notify = 45000

[jobs]
format = '\[[$symbol$number](blue)\]'
symbol_threshold = 1
number_threshold = 2
symbol = '✦'

[shlvl]
format = '\[[$symbol$shlvl](green)\]'
symbol = ''
disabled = false


# SPECIAL

[fill]
symbol = '─'

[character]
format = '$symbol '
success_symbol = '[❯](bold)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_visual_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold red)'
vimcmd_replace_one_symbol = '[](bold red)'
