" indent & spacing
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set smarttab
set softtabstop=4
set expandtab
set shiftround

" words, searching
set nohlsearch
set ignorecase
set smartcase
set incsearch
set iskeyword+=-

" scrolling
set scrolloff=6
set sidescroll=4
set sidescrolloff=8
set smoothscroll

" cmdline, statusline & statuscolumn
set showcmdloc=statusline
set laststatus=3
set cmdheight=1
set numberwidth=1
set shortmess=acCoOsSWF
set number
set signcolumn=auto:1

" folding
set foldclose=
set foldlevel=6
set foldnestmax=11
set foldtext=
set viewoptions=cursor,folds

" terminal, cursor & gui
set pumheight=15
set pumborder=rounded
set termguicolors
set startofline
set mouse=a
set helpheight=25
set nowrap
set linebreak
set breakindent
set guicursor=n-sm-r:block,v-o-i-c-ci-cr:ver100

" others
set concealcursor=n
set notimeout
set swapfile
set nowritebackup
set confirm
set list
set nrformats=blank
"set listchars=leadmultispace:│   ,tab:> ,trail: ,exts:…,precedes:…,conceal:●
"set fillchars=stl: ,fold: ,folpen:,foldclose:,msgsep:─,eob: ,lastline:.,diff:╱

let g:mapleader=" "

map <c-up> <cmd>bp<cr>
map <c-down> <cmd>bn<cr>
imap <c-up> <cmd>bp<cr>
imap <c-down> <cmd>bn<cr>
map <c-k> <cmd>bp<cr>
map <c-j> <cmd>bn<cr>
imap <c-k> <cmd>bp<cr>
imap <c-j> <cmd>bn<cr>

" deleting & registers
"nmap _ "_
"nmap s "_s
"nmap x "_x
"vmap p "_dp
"nmap <del> "_x
nmap cn *``"_cgn
nmap <bs> X
nmap <cr> "_ciw
nmap r <cmd>silent redo<cr>

nmap q <cmd>q<cr>
nmap <leader>w <cmd>silent w<bar>redraw <cr>
nmap <leader>W <cmd>silent w<bar>redraw <cr>

" indent & fold
nmap = ==
nmap > >>
nmap < <<
vmap > >gv
vmap < <gv

" toggles
nmap zs <cmd>setlocal spell!<cr>
nmap zw <cmd>setlocal wrap!<cr>

" other
vmap . :norm .<cr>
nmap ; @:
nmap go jA
nmap gj @='j^"_d0kgJ'<cr>
nmap z= 1z=

" cmdline & abbreviations
cmap <c-j> <down>
cmap <c-k> <up>
