# https://wiki.archlinux.org/title/Aria2


# GENERAL

continue
log-level=warn
max-connection-per-server=4
min-split-size=30M
split=4
max-concurrent-downloads=4
console-log-level=error
download-result=full
summary-interval=0
max-tries=3
max-connection-per-server=1
download-result=hide

# TORRENT

bt-tracker="udp://ipv4announce.sktorrent.eu:6969/announce"
bt-tracker="udp://martin-gebhardt.eu:25/announce"
bt-tracker="udp://open.demonii.com:1337/announce"
bt-tracker="udp://open.stealth.si:80/announce"
bt-tracker="udp://seedpeer.net:6969/announce"
bt-tracker="udp://t.overflow.biz:6969/announce"
bt-tracker="udp://tr4ck3r.duckdns.org:6969/announce"
bt-tracker="udp://tracker-udp.gbitt.info:80/announce"
bt-tracker="udp://tracker.004430.xyz:1337/announce"
bt-tracker="udp://tracker.bittor.pw:1337/announce"
bt-tracker="udp://tracker.corpscorp.online:80/announce"
bt-tracker="udp://tracker.gmi.gd:6969/announce"
bt-tracker="udp://tracker.opentrackr.org:1337/announce"
bt-tracker="udp://tracker.qu.ax:6969/announce"
bt-tracker="udp://tracker.srv00.com:6969/announce"
bt-tracker="udp://tracker.theoks.net:6969/announce"
bt-tracker="udp://tracker.torrent.eu.org:451/announce"
bt-tracker="udp://tracker.tryhackx.org:6969/announce"
bt-tracker="udp://utracker.ghostchu-services.top:6969/announce"
bt-tracker="udp://wepzone.net:6969/announce"

max-overall-upload-limit=2M
