# https://wiki.archlinux.org/title/Aria2


# GENERAL

continue=true
log-level=warn
max-connection-per-server=4
min-split-size=30M
split=4
max-concurrent-downloads=4
console-log-level=error
download-result=full
summary-interval=0
max-tries=3
max-connection-per-server=1
download-result=hide

# TORRENT

# nyaa default trackers
bt-tracker=http://nyaa.tracker.wf:7777/announce
bt-tracker=udp://open.stealth.si:80/announce
bt-tracker=udp://tracker.opentrackr.org:1337/announce
bt-tracker=udp://exodus.desync.com:6969/announce
bt-tracker=udp://tracker.torrent.eu.org:451/announce

# read! curl -L https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt 2>/dev/null | sed '/^$/d; s/^/bt-tracker=/' | sort
bt-tracker=udp://ipv4announce.sktorrent.eu:6969/announce
bt-tracker=udp://martin-gebhardt.eu:25/announce
bt-tracker=udp://open.demonii.com:1337/announce
bt-tracker=udp://open.stealth.si:80/announce
bt-tracker=udp://retracker01-msk-virt.corbina.net:80/announce
bt-tracker=udp://seedpeer.net:6969/announce
bt-tracker=udp://t.overflow.biz:6969/announce
bt-tracker=udp://torrentclub.online:54123/announce
bt-tracker=udp://torrents.tmtime.dev:6969/announce
bt-tracker=udp://tr4ck3r.duckdns.org:6969/announce
bt-tracker=udp://tracker-udp.gbitt.info:80/announce
bt-tracker=udp://tracker.004430.xyz:1337/announce
bt-tracker=udp://tracker.auctor.tv:6969/announce
bt-tracker=udp://tracker.bittor.pw:1337/announce
bt-tracker=udp://tracker.bluefrog.pw:2710/announce
bt-tracker=udp://tracker.corpscorp.online:80/announce
bt-tracker=udp://tracker.ducks.party:1984/announce
bt-tracker=udp://tracker.gmi.gd:6969/announce
bt-tracker=udp://tracker.hismz.cn:6969/announce
bt-tracker=udp://tracker.opentorrent.top:6969/announce
bt-tracker=udp://tracker.opentrackr.org:1337/announce
bt-tracker=udp://tracker.publictracker.xyz:6969/announce
bt-tracker=udp://tracker.qu.ax:6969/announce
bt-tracker=udp://tracker.srv00.com:6969/announce
bt-tracker=udp://tracker.theoks.net:6969/announce
bt-tracker=udp://tracker.torrent.eu.org:451/announce
bt-tracker=udp://tracker.tryhackx.org:6969/announce
bt-tracker=udp://tracker.wildkat.net:6969/announce
bt-tracker=udp://utracker.ghostchu-services.top:6969/announce
bt-tracker=udp://wepzone.net:6969/announce
bt-tracker=udp://zer0day.ch:1337/announce

max-overall-upload-limit=2M

# HOOKS

on-bt-download-complete=notif-bt
