#:schema https://yazi-rs.github.io/schemas/keymap.json
# tombi: format.rules.table-keys-order.disabled = true

help.prepend_keymap = [{ on = "q", run = "close", desc = "Exit the process" }]
tasks.prepend_keymap = [{ on = "q", run = "close", desc = "Close the spot" }]
spot.prepend_keymap = [{ on = "q", run = "close", desc = "Close the spot" }]

[pick]
prepend_keymap = [
  { on = "l", run = "close --submit" },
  { on = "<right>", run = "close --submit" },
  { on = "<C-m>", run = "close --submit" },
]

[mgr]
prepend_keymap = [
  { on = "g", run = "arrow top", desc = "Move cursor to the top" },
  # plugins
  { on = ["s", "t"], run = "plugin max-pane" },
  { on = "f", run = "plugin fchar start", desc = "Jump to first char in filename" },
  { on = "F", run = "plugin fzf", desc = "fzf search" },
  { on = "z", run = "plugin zoxide", desc = "Jump to a directory using zoxide" },
  { on = "l", run = "plugin smart-enter" },
  { on = "{", run = "plugin nextension bwd" },
  { on = "}", run = "plugin nextension fwd" },
  { on = "<right>", run = "plugin smart-enter" },
  # Selection
  { on = "%", run = "toggle_all --state=true", desc = "Select all" },
  # Operation
  { on = "o", run = "open --interactive" },
  { on = "O", run = "create" },
  { on = "d", run = "remove", desc = "Trash selected files" },
  { on = "d", run = "remove --permanently", desc = "Delete selected files" },
  { on = "D", run = '''shell --block --confirm -- fd -HI -td -d2 -x rmdir -p''', desc = "purge empty directories" },
  { on = ["y", "y"], run = "yank", desc = "yank file" },
  { on = ["y", "p"], run = "copy path", desc = "yank ENTIRE path" },
  { on = ["y", "f"], run = "copy filename", desc = "yank filename" },
  { on = ["y", "u"], run = "shell --confirm -- wl-copy -t text/uri-list file://$(realpath \"$0\")", desc = "yank uri" },
  { on = "p", run = ["paste", "unyank"], desc = "Paste yanked files" },
  # Tabs
  { on = "t", run = ["tab_create --current", "tab_rename ''", "plugin zoxide"], desc = "Create a new tab with CWD" },
  { on = "T", run = "tab_rename --interactive", desc = "Rename current tab" },
  { on = "<C-Left>", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
  { on = "<C-Right>", run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
  # Help
  { on = "?", run = "help", desc = "Open help" },
  # rename
  { on = "@", run = ''' shell --block --confirm -- rat "$0" ''', for = "android" },
  { on = "I", run = "rename --cursor=start --hovered" },
  { on = "i", run = "rename --cursor=before_ext --hovered" },
  { on = "a", run = "rename --cursor=end --hovered" },
  { on = "A", run = "rename --cursor=end --hovered" },
  { on = "r", run = "rename --cursor=before_ext" },
  { on = "R", run = ["toggle_all", "rename", "escape"] },
  { on = ["c", "c"], run = "rename --empty=all", desc = "rename empty" },
  { on = ["c", "0"], run = "rename --empty=stem --cursor=start", desc = "rename stem" },
  { on = ["c", "o"], run = "rename --empty=stem --cursor=start", desc = "rename stem" },
  { on = ["c", "^"], run = "rename --empty=stem --cursor=start", desc = "rename stem" },
  { on = ["c", "$"], run = "rename --empty=ext --cursor=end", desc = "rename ext" },
  # sorting
  { on = ["s", "m"], run = "plugin sort-by-location mtime" },
  { on = ["s", "s"], run = ["plugin sort-by-location size", "linemode size"] },
  { on = ["s", "e"], run = "plugin sort-by-location extension" },
  { on = ["s", "n"], run = "plugin sort-by-location natural" },
  # other
  { on = "<C-g>", run = '''shell --block --confirm -- nvim +Pick\ grep_live''', desc = "rg search" },
  { on = "<Esc>", run = ["escape", "unyank"], desc = "Exit visual mode, clear selection, or cancel search" },
]
