theme = "custom"

# TODO: search all columns by default
[editor]
middle-click-paste = false
default-yank-register = "+"
shell = ["fish", "--no-config", "-c"]
cursorline = true
continue-comments = false
auto-format = true
completion-replace = true
true-color = true
bufferline = "multiple"
color-modes = true
text-width = 85
atomic-save = true
popup-border = "all"
jump-label-alphabet = "fjdksla;ghcnvmwi"
end-of-line-diagnostics = "hint"
smart-tab.enable = false
indent-guides = { render = true, skip-levels = 1 }
gutters = { layout = ["diff", "line-numbers", "spacer"], line-numbers.min-width = 1 }
cursor-shape = { insert = "bar", select = "underline" }
whitespace = { render = { tab = "all", newline = "all" }, characters = { tab = ">", tabpad = " " } }
inline-diagnostics = { cursor-line = "disable", other-lines = "disable" }
lsp = { display-progress-messages = true }
file-picker = { follow-symlinks = false, git-ignore = true, max-depth = 5 }

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "diagnostics"]
right = ["selections", "register", "position-percentage", "file-encoding", "spacer"]
separator = " "

# TODO: C/D
# TODO: +/- toggle text
# TODO: q -> save line:col info
# TODO: q -> :buffer-close when #buf > 1
# TODO: load line:col info from wrapper
# TODO: repeat last thing on ;
# TODO: C-n to select node

[keys.insert]
"C-n" = "completion"

[keys.normal]
"$" = ["extend_to_line_end"]
# "*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"^" = ["extend_to_first_nonwhitespace"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"]".h = ["goto_next_change"]
"[".h = ["goto_prev_change"]
"C-j" = [":buffer-next"]
"C-k" = [":buffer-previous"]
"C-r" = [":config-reload"]
"C-v" = ["copy_selection_on_next_line"]
"C-c" = [":buffer-close"]
"esc" = ["collapse_selection", "keep_primary_selection"]
"ret" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "select_mode"]
0 = ["extend_to_line_start"]
D = ["extend_to_line_end", "delete_selection"]
C = ["extend_to_line_end", "change_selection"]
Y = ["collapse_selection", "extend_to_line_end", "yank", "flip_selections"]
Q = ["copy_selection_on_next_line"]
# G = ["goto_file_end"]
q = [":quit"]
r = ["redo"]
M = ["select_textobject_around"]
U = [":reset-diff-change"]
V = ["extend_line_below"]
X = ["extend_line_above"]

[keys.normal.m]
# '"' = ["select_textobject_inner", '"']
# m = ["select_mode", "match_brackets"]

[keys.normal.space]
":" = "command_palette"
h = "command_palette"
w = ":w"
d = ":toggle-option inline-diagnostics.other-lines warning disable"
# t = { s = ":tree-sitter-scopes", h = ":tree-sitter-highlight-name" }

[keys.select]
"$" = "extend_to_line_end"
"^" = "extend_to_first_nonwhitespace"
"ret" = "select_line_below"
m = ["select_mode", "match_brackets"]
o = "flip_selections"
