# htps://github.com/helix-editor/helix/wiki/Language-Server-Configurations

language = [
  { name = "fish", auto-format = true, formatter = { command = "fish_indent" } },
  {
    name = "git-config",
    file-types = [
      "gitconfig",
      { glob = ".gitmodules" },
      { glob = "gitconfig" },
      { glob = ".gitconfig" },
      { glob = ".git/config" },
      { glob = ".config/git/config" },
      { glob = ".git/modules/*/config" },
      { glob = "config.worktree" },
      { glob = ".lfsconfig" },
      { glob = "git/config" },
      { glob = "git/delta.conf" },
    ]
  },
  { name = "ini", file-types = ["ini", "conf"] },
  { name = "kanata", scope = "source.kanata", file-types = ["kbd"], comment-tokens = [";;"] },
  {
    name = "lua",
    # workspace-lsp-roots = [".luarc.json"],
    roots = [
      ".luarc.json",
      ".luacheckrc",
      ".stylua.toml",
      "selene.toml",
    ],
    auto-format = true,
    # TODO: fix stylua giving os err 2
    formatter = {
      command = "stylua",
      args = ["-f", "%sh{printenv HOME}/repos/dotfiles/other/stylua.toml", "-"],
    }
  },
  { name = "pkgbuild", file-types = [{ glob = "build.sh" }] },
  { name = "python", auto-format = true },
  # { name = "rust", language-servers = [] },
  { name = "toml", auto-format = true },
  {
    name = "typst",
    auto-format = true,
    injection-regex = "typ(st|c)?",
    # code-actions-on-save = ['tinymist.exportPdf "%sh{realpath %{buffer_name}}"']
  },
]

grammar = [
  {
    name = "kanata",
    source = {
      git = "https://codeberg.org/AminurAlam/tree-sitter-kanata",
      rev = "04a75edb2cb446d5863dadfac3dacceb2aa07de0"
    }
  },
]

# TODO: fix pdf export and preview
[Language-server.tinymist.config]
# :lsp-workspace-command tinymist.exportPdf "%sh{realpath %{buffer_name}}"
exportPdf = "onSave"
formatterMode = "typstyle"
formatterPrintWidth = 85
formatterProseWrap = true
lint = { enabled = true }
syntaxOnly = "disable"
# preview.background.enabled = true
# preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"]

[Language-server.rust-analyzer.config.rust-analyzer]
linkedProjects = []

[language-server.ruff.config.init_options]
settings = { configuration = ".config/ruff/ruff.toml" }

[language-server.lua-language-server.config.Lua]
format.enable = false
semantic.enable = false
telemetry.enable = false
window.progressBar = true
workspace.checkThirdParty = false
codeLens.enable = true
completion = { callSnippet = "Replace", displayContext = 5 }
diagnostics = {
  disable = ["lowercase-global"],
  globals = ["_G", "vim"],
  libraryFiles = "disable",
  unusedLocalExclude = ["_*"]
}
hint = {
  enable = true,
  semicolon = "Disable",
  arrayIndex = "Enable",
  setType = true,
  paramName = "All",
  paramType = true,
  await = true
}
