# htps://github.com/helix-editor/helix/wiki/Language-Server-Configurations

language = [
  { name = "fish", auto-format = true },
  { name = "handlebars", scope = "source.handlebars", file-types = ["handlebars"] },
  { name = "kanata", scope = "source.kanata", file-types = ["kbd"], comment-tokens = [";;"] },
  { name = "kdl", auto-format = true },
  { name = "lua", roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml"], auto-format = true },
  { name = "markdown", auto-format = true, formatter = { command = "prettier", args = ["--parser", "markdown"] } },
  { name = "newsraft", scope = "source.newsraft", file-types = [{ glob = "newsraft/feeds" }] },
  { name = "pkgbuild", auto-format = true, file-types = [{ glob = "PKGBUILD" }, { glob = "build.sh" }] },
  { name = "python", auto-format = true },
  # { name = "rust", language-servers = [] },
  { name = "toml", auto-format = true },
  { name = "typst", auto-format = true },
  { name = "zathurarc", scope = "source.zathura", file-types = [{ glob = "zathurarc" }] }
]

grammar = [
  { name = "handlebars", source.path = "/home/fisher/repos/tree-sitter/tree-sitter-handlebars" },
  { name = "kanata", source.path = "/home/fisher/repos/tree-sitter/kanata" },
  { name = "newsraft", source.path = "/home/fisher/repos/tree-sitter/newsraft" },
  { name = "zathurarc", source.path = "/home/fisher/repos/tree-sitter/zathurarc" }
]

# TODO: fix pdf export and preview
[Language-server.tinymist.config]
# :lsp-workspace-command tinymist.exportPdf "%sh{realpath %{buffer_name}}"
exportPdf = "onSave"
formatterMode = "typstyle"
formatterPrintWidth = 85
formatterProseWrap = true
lint.enabled = true
syntaxOnly = "disable"
# preview.background.enabled = true
# preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"]

[language-server.ruff.config.init_options]
settings.configuration = ".config/ruff/ruff.toml"

[language-server.lua-language-server.config.Lua]
format.enable = false
semantic.enable = false
telemetry.enable = false
window.progressBar = true
workspace.checkThirdParty = false
codeLens.enable = true
completion = { callSnippet = "Replace", displayContext = 5 }
diagnostics = { libraryFiles = "disable", unusedLocalExclude = ["_*"] }
hint.semicolon = "Disable"

[language-server.rust-analyzer.config]
assist.expressionFillDefault = "default"
cachePriming.enable = false
cargo.extraArgs = ["--profile", "rust-analyzer"]
check.command = "clippy"
checkOnSave = false
completion.fullFunctionSignatures.enable = true
diagnostics.enable = true
imports.granularity.group = "item"
lens.run.enable = false
linkedProjects = []
lru.capacity = 256
procMacro.enable = true
semanticHighlighting.operator.specialization.enable = true
semanticHighlighting.punctuation.enable = true
semanticHighlighting.punctuation.separate.macro.bang = true
signatureInfo.documentation.enable = true
typing.autoClosingAngleBrackets.enable = true

[language-server.rust-analyzer.config.inlayHints]
bindingModeHints.enable = true
closureCaptureHints.enable = true
closureStyle = "rust_analyzer"
expressionAdjustmentHints.enable = "reborrow"
expressionAdjustmentHints.mode = "prefer_postfix"
lifetimeElisionHints.useParameterNames = true
parameterHints.enable = true
rangeExclusiveHints.enable = true
renderColons = false

[language-server.rust-analyzer.config.cargo.extraEnv]
CARGO_PROFILE_RUST_ANALYZER_CODEGEN_UNITS = "256"
CARGO_PROFILE_RUST_ANALYZER_INCREMENTAL = "true"
CARGO_PROFILE_RUST_ANALYZER_INHERITS = "dev"
CARGO_PROFILE_RUST_ANALYZER_OPT_LEVEL = "0"
