# htps://github.com/helix-editor/helix/wiki/Language-Server-Configurations

language = [
  { name = "fish", auto-format = true, formatter = { command = "fish_indent" } },
  { name = "ini", file-types = ["ini", "conf"] },
  { name = "kanata", scope = "source.kanata", file-types = ["kbd"], comment-tokens = [";;"] },
  {
    name = "lua",
    auto-format = true,
    formatter = { command = "stylua", args = ["-f", "repos/dotfiles/other/stylua.toml", "-"] }
  },
  { name = "pkgbuild", file-types = [{ glob = "build.sh" }] },
  { name = "python", auto-format = true },
  # { name = "rust", language-servers = [] },
  { name = "toml", auto-format = true },
  { name = "typst", injection-regex = "typ(st|c)?" },
]

grammar = [
  {
    name = "kanata",
    source = {
      git = "https://codeberg.org/AminurAlam/tree-sitter-kanata",
      rev = "04a75edb2cb446d5863dadfac3dacceb2aa07de0"
    }
  },
]

[Language-server.tinymist.config]
exportPdf = "onType"
formatterMode = "typstyle"
formatterPrintWidth = 85
formatterProseWrap = true
lint = { enabled = true }
syntaxOnly = "disable"

[Language-server.rust-analyzer.config.rust-analyzer]
linkedProjects = []

[language-server.ruff.config.init_options]
settings = { configuration = ".config/ruff/ruff.toml" }

[language-server.lua-language-server.config.Lua]
format.enable = false
semantic.enable = false
telemetry.enable = false
window.progressBar = true
workspace.checkThirdParty = false
codeLens.enable = true
completion = { callSnippet = "Replace", displayContext = 5 }
diagnostics = {
  disable = ["lowercase-global"],
  globals = ["_G", "vim"],
  libraryFiles = "disable",
  unusedLocalExclude = ["_*"]
}
hint = {
  enable = true,
  semicolon = "Disable",
  arrayIndex = "Enable",
  setType = true,
  paramName = "All",
  paramType = true,
  await = true
}
