abbr cp "cp -ivr"
abbr mv "mv -iv"
abbr rm "rm -i"
abbr rf "rm -rfI"
abbr rd "rmdir -pv"
abbr md "mkdir -pv"
abbr vi "nvim"
abbr cls "clear"
abbr cal "cal -my"
abbr qmv "qmv -f do"
abbr wget "wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"

abbr -ag gup "git add . && git commit && git push origin"
abbr -ag gcp "git clone --depth 1"

abbr -ag gd "git diff"
abbr -ag ga "git status -s"
abbr -ag gs "git status -s"
abbr -ag gc "git checkout"
abbr -ag grau "git remote add upstream"
abbr -ag gp "git pull origin"
