local set = vim.opt

set.tabstop = 2
set.shiftwidth = 2
set.softtabstop = 2
set.autoindent = true
set.smartindent = true
set.smarttab = true
set.expandtab = true
set.shiftround = true
set.conceallevel = 2
set.concealcursor = 'n'
set.spell = true
set.commentstring = '- %s'

vim.cmd [[
iabbrev -> →
iabbrev alpha α
iabbrev kappa κ
iabbrev digamma ϝ
iabbrev Delta ∆
iabbrev Theta Θ
iabbrev beta β
iabbrev lambda λ
iabbrev rho ρ
iabbrev varepsilon ε
iabbrev Gamma Γ
iabbrev Upsilon Υ
iabbrev chi χ
iabbrev mu µ
iabbrev sigma σ
iabbrev varkappa κ
iabbrev Lambda Λ
iabbrev Xi Ξ
iabbrev delta δ
iabbrev nu ν
iabbrev tau τ
iabbrev varphi ϕ
iabbrev Omega Ω
iabbrev epsilon ϵ
iabbrev theta θ
iabbrev varpi ϖ
iabbrev Phi Φ
iabbrev aleph ℵ
iabbrev eta η
iabbrev omega ω
iabbrev upsilon υ
iabbrev varrho ϱ
iabbrev Pi Π
iabbrev beth ℶ
iabbrev gamma γ
iabbrev phi φ
iabbrev xi ξ
iabbrev varsigma ς
iabbrev Psi Ψ
iabbrev daleth ℸ
iabbrev iota ι
iabbrev pi π
iabbrev zeta ζ
iabbrev vartheta ϑ
iabbrev Sigma Σ
iabbrev gimel ג
iabbrev equiv ≡
iabbrev leq ≤
iabbrev geq ≥
iabbrev subset ⊂
iabbrev supset ⊃
iabbrev subseteq ⊆
iabbrev supseteq ⊇
iabbrev sum ∑
]]
