return {
    'wbthomason/packer.nvim',
    'nvim-lua/plenary.nvim',
    'kyazdani42/nvim-web-devicons',
    'nvim-telescope/telescope.nvim',
    'nvim-treesitter/nvim-treesitter',
    'lewis6991/impatient.nvim',
    { 'cvigilv/esqueleto.nvim', branch = 'develop' },
    'lukas-reineke/indent-blankline.nvim',
    { 'folke/tokyonight.nvim', module = false },
    'nvim-lualine/lualine.nvim',
    'goolord/alpha-nvim',
    'stevearc/dressing.nvim',
    'ghillb/cybu.nvim',
    'NvChad/nvim-colorizer.lua',
    'folke/which-key.nvim',
    'mong8se/actually.nvim',
    'kylechui/nvim-surround',
    'numToStr/Comment.nvim',
    'windwp/nvim-autopairs',
    'folke/trouble.nvim',
    'neovim/nvim-lspconfig',
    'hrsh7th/nvim-cmp',
    'hrsh7th/cmp-nvim-lsp',
    'hrsh7th/cmp-nvim-lua',
    'hrsh7th/cmp-path',
    'hrsh7th/cmp-buffer',
    'hrsh7th/cmp-cmdline',
    'L3MON4D3/LuaSnip',
    'saadparwaiz1/cmp_luasnip',
    'rafamadriz/friendly-snippets',
}
